'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by wsdl, Version=2.0.50727.1432.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Web.Services.WebServiceBindingAttribute(Name:="CreateStringForHelpConsoleSoap", [Namespace]:="http://tempuri.org/")>  _
Partial Public Class CreateStringForHelpConsole
    Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
    
    Private checkTheLoginSiteOperationCompleted As System.Threading.SendOrPostCallback
    
    '''<remarks/>
    Public Sub New()
        MyBase.New
        Me.Url = "http://localhost:20961/site/CreateStringForHelpConsole.asmx"
    End Sub
    
    '''<remarks/>
    Public Event checkTheLoginSiteCompleted As checkTheLoginSiteCompletedEventHandler
    
    '''<remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/checkTheLoginSite", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
    Public Function checkTheLoginSite(ByVal loginKey As String, ByVal hostName As String, ByVal userName As String) As Boolean
        Dim results() As Object = Me.Invoke("checkTheLoginSite", New Object() {loginKey, hostName, userName})
        Return CType(results(0),Boolean)
    End Function
    
    '''<remarks/>
    Public Function BegincheckTheLoginSite(ByVal loginKey As String, ByVal hostName As String, ByVal userName As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("checkTheLoginSite", New Object() {loginKey, hostName, userName}, callback, asyncState)
    End Function
    
    '''<remarks/>
    Public Function EndcheckTheLoginSite(ByVal asyncResult As System.IAsyncResult) As Boolean
        Dim results() As Object = Me.EndInvoke(asyncResult)
        Return CType(results(0),Boolean)
    End Function
    
    '''<remarks/>
    Public Overloads Sub checkTheLoginSiteAsync(ByVal loginKey As String, ByVal hostName As String, ByVal userName As String)
        Me.checkTheLoginSiteAsync(loginKey, hostName, userName, Nothing)
    End Sub
    
    '''<remarks/>
    Public Overloads Sub checkTheLoginSiteAsync(ByVal loginKey As String, ByVal hostName As String, ByVal userName As String, ByVal userState As Object)
        If (Me.checkTheLoginSiteOperationCompleted Is Nothing) Then
            Me.checkTheLoginSiteOperationCompleted = AddressOf Me.OncheckTheLoginSiteOperationCompleted
        End If
        Me.InvokeAsync("checkTheLoginSite", New Object() {loginKey, hostName, userName}, Me.checkTheLoginSiteOperationCompleted, userState)
    End Sub
    
    Private Sub OncheckTheLoginSiteOperationCompleted(ByVal arg As Object)
        If (Not (Me.checkTheLoginSiteCompletedEvent) Is Nothing) Then
            Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
            RaiseEvent checkTheLoginSiteCompleted(Me, New checkTheLoginSiteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
        End If
    End Sub
    
    '''<remarks/>
    Public Shadows Sub CancelAsync(ByVal userState As Object)
        MyBase.CancelAsync(userState)
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")>  _
Public Delegate Sub checkTheLoginSiteCompletedEventHandler(ByVal sender As Object, ByVal e As checkTheLoginSiteCompletedEventArgs)

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code")>  _
Partial Public Class checkTheLoginSiteCompletedEventArgs
    Inherits System.ComponentModel.AsyncCompletedEventArgs
    
    Private results() As Object
    
    Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
        MyBase.New(exception, cancelled, userState)
        Me.results = results
    End Sub
    
    '''<remarks/>
    Public ReadOnly Property Result() As Boolean
        Get
            Me.RaiseExceptionIfNecessary
            Return CType(Me.results(0),Boolean)
        End Get
    End Property
End Class
