'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by wsdl, Version=2.0.50727.1432.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Web.Services.WebServiceBindingAttribute(Name:="HelpConsoleAccessLogSoap", [Namespace]:="http://tempuri.org/")>  _
Partial Public Class HelpConsoleAccessLog
    Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
    
    Private saveAccessLogOperationCompleted As System.Threading.SendOrPostCallback
    
    '''<remarks/>
    Public Sub New()
        MyBase.New
        Me.Url = "http://tutorial.goldkeysolutions.com/HelpConsoleAccessLog.asmx"
    End Sub
    
    '''<remarks/>
    Public Event saveAccessLogCompleted As saveAccessLogCompletedEventHandler
    
    '''<remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/saveAccessLog", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
    Public Sub saveAccessLog(ByVal hostName As String, ByVal loginUser As String, ByVal loginApplication As String, ByVal code As String)
        Me.Invoke("saveAccessLog", New Object() {hostName, loginUser, loginApplication, code})
    End Sub
    
    '''<remarks/>
    Public Function BeginsaveAccessLog(ByVal hostName As String, ByVal loginUser As String, ByVal loginApplication As String, ByVal code As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("saveAccessLog", New Object() {hostName, loginUser, loginApplication, code}, callback, asyncState)
    End Function
    
    '''<remarks/>
    Public Sub EndsaveAccessLog(ByVal asyncResult As System.IAsyncResult)
        Me.EndInvoke(asyncResult)
    End Sub
    
    '''<remarks/>
    Public Overloads Sub saveAccessLogAsync(ByVal hostName As String, ByVal loginUser As String, ByVal loginApplication As String, ByVal code As String)
        Me.saveAccessLogAsync(hostName, loginUser, loginApplication, code, Nothing)
    End Sub
    
    '''<remarks/>
    Public Overloads Sub saveAccessLogAsync(ByVal hostName As String, ByVal loginUser As String, ByVal loginApplication As String, ByVal code As String, ByVal userState As Object)
        If (Me.saveAccessLogOperationCompleted Is Nothing) Then
            Me.saveAccessLogOperationCompleted = AddressOf Me.OnsaveAccessLogOperationCompleted
        End If
        Me.InvokeAsync("saveAccessLog", New Object() {hostName, loginUser, loginApplication, code}, Me.saveAccessLogOperationCompleted, userState)
    End Sub
    
    Private Sub OnsaveAccessLogOperationCompleted(ByVal arg As Object)
        If (Not (Me.saveAccessLogCompletedEvent) Is Nothing) Then
            Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
            RaiseEvent saveAccessLogCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
        End If
    End Sub
    
    '''<remarks/>
    Public Shadows Sub CancelAsync(ByVal userState As Object)
        MyBase.CancelAsync(userState)
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")>  _
Public Delegate Sub saveAccessLogCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
