USETEXTLINKS = 1
STARTALLOPEN = 0
HIGHLIGHT = 1
HIGHLIGHT_BG = '#808080'
ICONPATH = 'skinimages/'
GLOBALTARGET = 'R'
foldersTree = gFld('', '')
foldersTree.iconSrc = ICONPATH + 'ftv2blank.gif'
foldersTree.treeID = 'Tree1'

xWelcome = insFld(foldersTree, gFld('Welcome', 'Welcome.htm'))
insDoc(xWelcome, gLnk('R', 'Ask', 'Ask.htm'))
xInstallation = insFld(foldersTree, gFld('Installation', 'Installation.htm'))
insDoc(xInstallation, gLnk('R', 'System&nbsp;Requirements', 'System_Requirements.htm'))
xBasic_Functions = insFld(foldersTree, gFld('Basic&nbsp;Functions', 'Basic_Functions.htm'))
insDoc(xBasic_Functions, gLnk('R', 'Screen&nbsp;Overview', 'screen_overview.htm'))
insDoc(xBasic_Functions, gLnk('R', 'Contacts', 'Contacts.htm'))
insDoc(xBasic_Functions, gLnk('R', 'Events', 'events.htm'))
insDoc(xBasic_Functions, gLnk('R', 'Logbook', 'Logbook.htm'))
insDoc(xBasic_Functions, gLnk('R', 'Messages', 'messages.htm'))
insDoc(xBasic_Functions, gLnk('R', 'Profiles', 'profiles.htm'))
xAdvanced_Functions = insFld(foldersTree, gFld('Advanced&nbsp;Functions', 'Advanced_Functions.htm'))
insDoc(xAdvanced_Functions, gLnk('R', 'Administration', 'Advanced_Function_1.htm'))
insDoc(xAdvanced_Functions, gLnk('R', 'Contact&nbsp;List&nbsp;Keywords', 'contact_list_keywords.htm'))
insDoc(xAdvanced_Functions, gLnk('R', 'Event&nbsp;Types', 'event_types.htm'))
insDoc(xAdvanced_Functions, gLnk('R', 'Logbook&nbsp;Categories', 'logbook_categories.htm'))
insDoc(xAdvanced_Functions, gLnk('R', 'The&nbsp;Data&nbsp;Entry&nbsp;Panel', 'the_data_entry_panel.htm'))
insDoc(xAdvanced_Functions, gLnk('R', 'Profile&nbsp;Indicators', 'profile_indicators.htm'))
insDoc(xAdvanced_Functions, gLnk('R', 'Concierge&nbsp;Staff', 'concierge_staff.htm'))
insDoc(xAdvanced_Functions, gLnk('R', 'Concierge&nbsp;White&nbsp;Board', 'concierge_white_board.htm'))
insDoc(xAdvanced_Functions, gLnk('R', 'White&nbsp;Board&nbsp;Usage', 'white_board_usage.htm'))
insDoc(xAdvanced_Functions, gLnk('R', 'Manage&nbsp;Messages', 'manage_messages.htm'))
insDoc(xAdvanced_Functions, gLnk('R', 'Configuration&nbsp;Options', 'configuration_options.htm'))
insDoc(xAdvanced_Functions, gLnk('R', 'Create&nbsp;Your&nbsp;Own&nbsp;Map', 'create_your_own_map.htm'))
xadd_ons = insFld(foldersTree, gFld('Add&nbsp;Ons', 'add_ons.htm'))
insDoc(xadd_ons, gLnk('R', 'Key&nbsp;Control', 'key_control.htm'))
insDoc(xadd_ons, gLnk('R', 'Lost&nbsp;and&nbsp;Found&nbsp;PDF&nbsp;Manual', 'docs/LostandFound.pdf'))
insDoc(foldersTree, gLnk('R', 'Reports', 'Advanced_Function_2.htm'))
xTutorials = insFld(foldersTree, gFld('Videos', 'Tutorials.htm'))
xcontact_lessons = insFld(xTutorials, gFld('Contacts&nbsp;Videos', 'contact_lessons.htm'))
insDoc(xcontact_lessons, gLnk('R', 'Add&nbsp;a&nbsp;Contact', 'Tutorial_1.htm'))
insDoc(xcontact_lessons, gLnk('R', 'Search&nbsp;Contacts', 'search_contacts.htm'))
xlogbook_lessons = insFld(xTutorials, gFld('Logbook&nbsp;Videos', 'logbook_lessons.htm'))
insDoc(xlogbook_lessons, gLnk('R', 'Add&nbsp;a&nbsp;Logbook&nbsp;Entry', 'add_a_logbook_entry.htm'))
insDoc(xlogbook_lessons, gLnk('R', 'Print&nbsp;A&nbsp;Confirmation', 'print_a_confirmation.htm'))
insDoc(xlogbook_lessons, gLnk('R', 'Print&nbsp;an&nbsp;Itinerary', 'print_an_itinerary.htm'))
xadd_ons_videos = insFld(xTutorials, gFld('Add&nbsp;Ons&nbsp;Videos', 'add_ons_videos.htm'))
insDoc(xadd_ons_videos, gLnk('R', 'Lost&nbsp;and&nbsp;Found&nbsp;Overview', 'lost_and_found_overview.htm'))
insDoc(xadd_ons_videos, gLnk('R', 'Key&nbsp;Control&nbsp;Overview', 'key_control_overview.htm'))
xadmin_videos = insFld(xTutorials, gFld('Admin&nbsp;Videos', 'admin_videos.htm'))
insDoc(xadmin_videos, gLnk('R', 'Property&nbsp;Logo', 'property_logo.htm'))
insDoc(foldersTree, gLnk('R', 'Documents', 'download_documents1.htm'))
insDoc(foldersTree, gLnk('R', 'PCI&nbsp;PA-DSS', 'pci_pa-dss.htm'))
xFAQ = insFld(foldersTree, gFld('FAQ', 'FAQ.htm'))
insDoc(xFAQ, gLnk('R', 'General&nbsp;FAQ', 'General_FAQ.htm'))
insDoc(xFAQ, gLnk('R', 'Installation&nbsp;FAQ', 'Installation_FAQ.htm'))
